### ISSUE TITLE
Geocoding

### ISSUE THREAD

**Issue by vtien** [bluebonnet-data/bbd#3]
### Motivation
It is often desirable to be able to transform addresses in VAN/Census data into latitude and longitude coordinates, thereby allowing a user to map voter information on top of geographical info. 

### Workflow Example:
Input dataset with address information as a column
Transform the address column into latitude and longitude coordinates
Overlay the latitude and longitude coordinates on top of a map (with ability to label lat/long coordinates according to other desired information, such as democrat/republican info)

### Proposal
Create a functionality through which a specified column can be transformed into geocoding data and then overlaid onto a map to visualize voters in a given district/area

**Comment by boom-roasted** [comment]
Cool! Looks like @inh2102 is working on the same feature in the R package (issue bluebonnet-data/bbd_r#1). Commenting to link these issues together.

**Comment by DarkSideOfTheMat** [comment]
I just added a submodule that does this using OpenStreetMaps free API Nominatim. It is a long process but a good trade-off for it being free.
